services:
  php:
    image: php:8.4-fpm
    container_name: php_lab
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/html
      - ./app/config/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug-custom.ini
    ports:
      - "33464:33464"